[package]
name = "api-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41", features = ["full"] }
axum = "0.7"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5", features = ["cors"] }
moka = { version = "0.12", features = ["future"] }
tracing = "0.1"
tracing-subscriber = "0.3"
parking_lot = "0.12"
once_cell = "1.19"
tower = "0.4"
bytes = "1.5"
http-body-util = "0.1"
axum-core = "0.4"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
