name: Deploy Hooks

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET requests to all Deploy Hooks
        env:
          FRANKFURT_DEPLOY_HOOK: ${{ secrets.FRANKFURT_DEPLOY_HOOK }}
          VIRGINIA_DEPLOY_HOOK: ${{ secrets.VIRGINIA_DEPLOY_HOOK }}
          OHIO_DEPLOY_HOOK: ${{ secrets.OHIO_DEPLOY_HOOK }}
          SINGAPORE_DEPLOY_HOOK: ${{ secrets.SINGAPORE_DEPLOY_HOOK }}
          OREGON_DEPLOY_HOOK: ${{ secrets.OREGON_DEPLOY_HOOK }}
        run: |
          hooks=(
            "$FRANKFURT_DEPLOY_HOOK"
            "$VIRGINIA_DEPLOY_HOOK"
            "$OHIO_DEPLOY_HOOK"
            "$SINGAPORE_DEPLOY_HOOK"
            "$OREGON_DEPLOY_HOOK"
          )

          for hook in "${hooks[@]}"; do
            echo "Triggering deploy hook: $hook"
            curl -fsSL -X GET "$hook" || echo "Failed to trigger $hook"
          done